services:
  # ---- PostgreSQL 1 (aloga database) ----
  pg1:
    build:
      context: ./pg-docker
      dockerfile: Dockerfile
    container_name: pg1
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      postgres
      -c archive_mode=on
      -c archive_command='pgbackrest --stanza=pg1 archive-push %p'
      -c wal_level=replica
    volumes:
      - ./pg1-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./pg1-socket:/var/run/postgresql
      - ./pgbackrest-conf-pg1/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
      - ./pgbackrest-repo:/var/lib/pgbackrest
    restart: unless-stopped

  # ---- PostgreSQL 2 ----
  pg2:
    build:
      context: ./pg-docker
      dockerfile: Dockerfile
    container_name: pg2
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      postgres
      -c archive_mode=on
      -c archive_command='pgbackrest --stanza=pg2 archive-push %p'
      -c wal_level=replica
    volumes:
      - ./pg2-data:/var/lib/postgresql/data
      - ./pg2-socket:/var/run/postgresql
      - ./pgbackrest-conf-pg2/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
      - ./pgbackrest-repo:/var/lib/pgbackrest
    restart: unless-stopped

  # ---- pgBackRest Backup Server ----
  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    container_name: pgbackrest
    volumes:
      - ./pg1-data:/var/lib/postgresql/data
      - ./pg2-data:/var/lib/postgresql/pg2-data
      - ./pg1-socket:/var/run/pg1-socket
      - ./pg2-socket:/var/run/pg2-socket
      - ./pgbackrest-repo:/var/lib/pgbackrest
      - ./backup/pgbackrest-conf/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
    restart: unless-stopped

  # ---- pgAdmin ----
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5436:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
