# pgBackRest Configuration — POC

[pg1]
pg1-path=/var/lib/postgresql/data
pg1-socket-path=/var/run/pg1-socket

[pg2]
pg1-path=/var/lib/postgresql/pg2-data
pg1-socket-path=/var/run/pg2-socket

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
repo1-retention-full-type=count
compress-type=zst
start-fast=y
process-max=2
log-level-console=info
log-level-file=detail
log-path=/var/log/pgbackrest
